name: "cde-linux-git-assignment"

services:
  postgres:
    image: postgres:14
    container_name: cde-bootcamp-assignment-postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=bootcamp
      - POSTGRES_PASSWORD=bootcamp
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
